import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Carousel from "@/components/Courasel";
import don from "../../public/images/tissue.jpeg";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Umundu Artivism | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Construction Notice */}
<section className="w-full bg-yellow-200 text-black text-center py-8">
  <p className="text-3xl font-bold tracking-wide">
    🚧 Website is still under construction. Some features may not be available. 🚧
  </p>
</section>

      <section className="w-screen h-full bg-white text-black">
        <div className="w-full flex justify-center sm:hidden xs:hidden"></div>

        <div className=" w-full p-7 flex justify-center">
          <Carousel />
        </div>
        <div className="grid grid-cols-6 gap-4 mt-4">
          <div className="col-start-2 col-span-4">
            <div className=" grid grid-cols-2 py-7">
              <div className=" flex justify-center">
                <h2 className="text-3xl sm:text-2xl text-[#dd9445]">
                  Our Impact
                </h2>
              </div>
              <div className=" text-start sm:text-sm sm:text-center text-base">
                <p>
                  At Umundu Artivism, we firmly believe in the transformative
                  potential of art to touch hearts, change minds, and spur
                  action. Our multifaceted approach involves the following key
                  components:
                </p>
              </div>
            </div>
            <hr className="h-px my-10 bg-gray-200 border-0 w-3/4 mx-auto dark:bg-gray-700" />
            <div className=" grid grid-cols-2 py-7">
              <div className=" text-start text-base sm:text-sm sm:text-center">
                <p>
                  We actively engage with communities and schools through
                  awareness campaigns, focusing on crucial topics like Sexual
                  and Gender-based Violence, Menstrual Hygiene, and Sexual and
                  Reproductive Health and Rights. Through interactive sessions,
                  we provide education and resources to empower individuals and
                  promote healthier practices.
                </p>
              </div>
              <div className=" flex justify-center">
                <h2 className="text-3xl text-[#dd9445] sm:text-2xl sm:ml-6">
                  Community Engagement
                </h2>
              </div>
            </div>
            <hr className="h-px my-10 bg-gray-200 border-0 w-3/4 mx-auto dark:bg-gray-700" />
            <div className=" grid grid-cols-2">
              <div className=" flex justify-center">
                <h2 className="text-3xl text-[#dd9445] sm:text-2xl">
                  Safe Haven
                </h2>
              </div>
              <div className=" text-start text-base sm:text-sm sm:text-center">
                <p>
                  In cases of extreme gender-based violence, we offer a secure
                  and supportive environment at our center. Victims can reside
                  with us for up to six months while receiving counseling and
                  vocational training, ensuring they gain the tools needed for
                  self-sufficiency. Art Awareness: Art as a Catalyst We use
                  compelling artistic creations, such as skits and performances,
                  to spark conversations within communities. These
                  thought-provoking pieces serve as a springboard for
                  discussions on important social issues.
                </p>
              </div>
            </div>
            <hr className="h-px my-10 bg-gray-200 border-0 w-3/4 mx-auto dark:bg-gray-700" />
            <br />

            <div className=" w-full text-center py-7">
              <h2 className="text-3xl text-[#dd9445] font-bold mx-auto">
                TALENT SEARCH: Nurturing Talent
              </h2>
              <p className=" text-start py-6">
                We are passionate about nurturing the creative talents of the
                individuals we work with. Our programs provide opportunities for
                artists and creatives to hone their skills and gain exposure in
                the broader creative world.
              </p>
              <ul className="list-outside list-disc text-start ml-4">
                <li>
                  We are looking for persons who believe that they can act,
                  sing, paint, do make-up, play an instrument, or can dance. If
                  you fall under any if these, feel free to contact us by
                  visiting the contact section.
                </li>
                <li>
                  Our talents on board are from the following areas:
                  <ul className="text-center list-inside list-decimal">
                    <li>The University of Embu</li>
                    <li>
                      Colleges and tertiary institutions within Embu county.
                    </li>
                    <li>Community members.</li>
                    <li>Family and Friends.</li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </div>
<div className="text-center text-[#dd9445] bg-orange-900 w-full h-96">
<h1 className=" py-4 text-base font-sans font-thin">&#39;&#39;The smallest act of kindness is worth more than the grandest intention&#39;&#39;</h1>

        <div class="grid grid-cols-4 gap-4 w-full h-full place-content-center ">
        
          <div class="col-start-2 col-span-2 flex flex-col w-full h-full justify-center">
          <h2 className=" text-3xl">Get Involved __</h2>
            <div className="p-4 w-full h-full flex justify-center gap-4">
            <Link href={'/donate'} className=" bg-[#dd9445] p-4 w-fit my-4 text-white text-center border hover:scale-125 transition duration-1000">Donate</Link>
            <Link href={'/donate'} className=" bg-[#dd9445] p-4 w-fit my-4 text-white border hover:scale-125 transition duration-1000">Maybe Later</Link>
            </div>
          </div>
          <div className=" col-start-3 col-span-2 "></div>
        </div>
        </div>
      </section>
    </>
  );
}
